package com.wy.vas.dao;

import com.wy.vas.domain.couponProduct;
import com.wy.vas.domain.couponProductExample;

public interface couponProductDao {
    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_product
     *
     * @ibatorgenerated
     */
    int countByExample(couponProductExample example);

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_product
     *
     * @ibatorgenerated
     */
    void insert(couponProduct record);

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_product
     *
     * @ibatorgenerated
     */
    void insertSelective(couponProduct record);
}