package com.wy.vas.dao;

import com.wy.vas.domain.CouponDetail;
import com.wy.vas.domain.CouponDetailExample;

public interface CouponDetailDao {
    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    int countByExample(CouponDetailExample example);

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    int deleteByPrimaryKey(String code, Integer id);

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    void insert(CouponDetail record);

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    void insertSelective(CouponDetail record);

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKeySelective(CouponDetail record);
}