package com.wy.vas.dao;

import com.wy.vas.domain.couponProduct;
import com.wy.vas.domain.couponProductCondition;
import java.sql.SQLException;

public interface couponProductDao {
    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_product
     *
     * @ibatorgenerated 2015-12-10 23:04:49
     */
    int countByCondition(couponProductCondition condition) throws SQLException;

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_product
     *
     * @ibatorgenerated 2015-12-10 23:04:49
     */
    int deleteByPrimaryKey(String code, Integer id) throws SQLException;

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_product
     *
     * @ibatorgenerated 2015-12-10 23:04:49
     */
    void insert(couponProduct record) throws SQLException;

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_product
     *
     * @ibatorgenerated 2015-12-10 23:04:49
     */
    void insertSelective(couponProduct record) throws SQLException;

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_product
     *
     * @ibatorgenerated 2015-12-10 23:04:49
     */
    int updateByPrimaryKeySelective(couponProduct record) throws SQLException;
}