package com.wy.vas.dao;

import com.wy.vas.domain.couponProduct;
import com.wy.vas.domain.couponProductExample;

public class couponProductDaoImpl implements couponProductDao {

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_product
     *
     * @ibatorgenerated
     */
    public int countByExample(couponProductExample example) {
        Integer count = (Integer)  getSqlMapClient().queryForObject("coupon_product.yrtz_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_product
     *
     * @ibatorgenerated
     */
    public void insert(couponProduct record) {
        getSqlMapClient().insert("coupon_product.yrtz_insert", record);
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_product
     *
     * @ibatorgenerated
     */
    public void insertSelective(couponProduct record) {
        getSqlMapClient().insert("coupon_product.yrtz_insertSelective", record);
    }
}