package com.wy.vas.dao;

import com.wy.vas.domain.CouponDetail;
import com.wy.vas.domain.CouponDetailExample;

public class CouponDetailDaoImpl implements CouponDetailDao {

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    public int countByExample(CouponDetailExample example) {
        Integer count = (Integer)  getSqlMapClient().queryForObject("coupon_detail.yrtz_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(String code, Integer id) {
        CouponDetail key = new CouponDetail();
        key.setCode(code);
        key.setId(id);
        int rows = getSqlMapClient().delete("coupon_detail.yrtz_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    public void insert(CouponDetail record) {
        getSqlMapClient().insert("coupon_detail.yrtz_insert", record);
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    public void insertSelective(CouponDetail record) {
        getSqlMapClient().insert("coupon_detail.yrtz_insertSelective", record);
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(CouponDetail record) {
        int rows = getSqlMapClient().update("coupon_detail.yrtz_updateByPrimaryKeySelective", record);
        return rows;
    }
}