package com.wy.vas.service;

import com.wy.vas.domain.couponProduct;
import com.wy.vas.domain.couponProductCondition;
import java.sql.SQLException;

public class couponProductServiceImpl implements couponProductService {

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_product
     *
     * @ibatorgenerated 2015-12-10 23:04:49
     */
    public int countByCondition(couponProductCondition condition) throws SQLException {
        Integer count = (Integer)  dao.queryForObject(coupon_product);
        return count.intValue();
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_product
     *
     * @ibatorgenerated 2015-12-10 23:04:49
     */
    public int deleteByPrimaryKey(String code, Integer id) throws SQLException {
        int rows = dao.delete(coupon_product);
        return rows;
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_product
     *
     * @ibatorgenerated 2015-12-10 23:04:49
     */
    public void insert(couponProduct record) throws SQLException {
        dao.insert(coupon_product);
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_product
     *
     * @ibatorgenerated 2015-12-10 23:04:49
     */
    public void insertSelective(couponProduct record) throws SQLException {
        dao.insert(coupon_product);
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_product
     *
     * @ibatorgenerated 2015-12-10 23:04:49
     */
    public int updateByPrimaryKeySelective(couponProduct record) throws SQLException {
        int rows = dao.update(coupon_product);
        return rows;
    }
}