package test.dao;

import java.util.List;
import test.model.Customer;
import test.model.CustomerExample;

public interface CustomerDAO {
    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qauth
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    int countByExample(CustomerExample example);

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qauth
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    int deleteByExample(CustomerExample example);

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qauth
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    int deleteByPrimaryKey(String cid);

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qauth
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    void insert(Customer record);

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qauth
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    void insertSelective(Customer record);

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qauth
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    List selectByExample(CustomerExample example);

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qauth
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    Customer selectByPrimaryKey(String cid);

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qauth
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    int updateByExampleSelective(Customer record, CustomerExample example);

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qauth
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    int updateByExample(Customer record, CustomerExample example);

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qauth
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qauth
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    int updateByPrimaryKey(Customer record);
}