package test.dao;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import test.model.Customer;
import test.model.CustomerExample;

public class CustomerDAOImpl extends SqlMapClientDaoSupport implements CustomerDAO {

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qauth
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public CustomerDAOImpl() {
        super();
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qauth
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public int countByExample(CustomerExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("qauth.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qauth
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public int deleteByExample(CustomerExample example) {
        int rows = getSqlMapClientTemplate().delete("qauth.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qauth
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public int deleteByPrimaryKey(String cid) {
        Customer key = new Customer();
        key.setCid(cid);
        int rows = getSqlMapClientTemplate().delete("qauth.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qauth
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public void insert(Customer record) {
        getSqlMapClientTemplate().insert("qauth.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qauth
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public void insertSelective(Customer record) {
        getSqlMapClientTemplate().insert("qauth.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qauth
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public List selectByExample(CustomerExample example) {
        List list = getSqlMapClientTemplate().queryForList("qauth.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qauth
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public Customer selectByPrimaryKey(String cid) {
        Customer key = new Customer();
        key.setCid(cid);
        Customer record = (Customer) getSqlMapClientTemplate().queryForObject("qauth.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qauth
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public int updateByExampleSelective(Customer record, CustomerExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("qauth.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qauth
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public int updateByExample(Customer record, CustomerExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("qauth.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qauth
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public int updateByPrimaryKeySelective(Customer record) {
        int rows = getSqlMapClientTemplate().update("qauth.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qauth
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public int updateByPrimaryKey(Customer record) {
        int rows = getSqlMapClientTemplate().update("qauth.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by yrtz.
     * This class corresponds to the database table qauth
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    private static class UpdateByExampleParms extends CustomerExample {
        private Object record;

        public UpdateByExampleParms(Object record, CustomerExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}