package test.dao;

import java.util.List;
import test.model.Qmenu;
import test.model.QmenuExample;

public interface QmenuDAO {
    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    int countByExample(QmenuExample example);

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    int deleteByExample(QmenuExample example);

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    int deleteByPrimaryKey(String cid);

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    void insert(Qmenu record);

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    void insertSelective(Qmenu record);

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    List selectByExample(QmenuExample example);

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    Qmenu selectByPrimaryKey(String cid);

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    int updateByExampleSelective(Qmenu record, QmenuExample example);

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    int updateByExample(Qmenu record, QmenuExample example);

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    int updateByPrimaryKeySelective(Qmenu record);

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    int updateByPrimaryKey(Qmenu record);
}