package test.dao;

import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import test.model.Qmenu;
import test.model.QmenuExample;

public class QmenuDAOImpl extends SqlMapClientDaoSupport implements QmenuDAO {

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public QmenuDAOImpl() {
        super();
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public int countByExample(QmenuExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("qmenu.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public int deleteByExample(QmenuExample example) {
        int rows = getSqlMapClientTemplate().delete("qmenu.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public int deleteByPrimaryKey(String cid) {
        Qmenu key = new Qmenu();
        key.setCid(cid);
        int rows = getSqlMapClientTemplate().delete("qmenu.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public void insert(Qmenu record) {
        getSqlMapClientTemplate().insert("qmenu.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public void insertSelective(Qmenu record) {
        getSqlMapClientTemplate().insert("qmenu.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public List selectByExample(QmenuExample example) {
        List list = getSqlMapClientTemplate().queryForList("qmenu.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public Qmenu selectByPrimaryKey(String cid) {
        Qmenu key = new Qmenu();
        key.setCid(cid);
        Qmenu record = (Qmenu) getSqlMapClientTemplate().queryForObject("qmenu.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public int updateByExampleSelective(Qmenu record, QmenuExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("qmenu.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public int updateByExample(Qmenu record, QmenuExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("qmenu.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public int updateByPrimaryKeySelective(Qmenu record) {
        int rows = getSqlMapClientTemplate().update("qmenu.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public int updateByPrimaryKey(Qmenu record) {
        int rows = getSqlMapClientTemplate().update("qmenu.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by yrtz.
     * This class corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    private static class UpdateByExampleParms extends QmenuExample {
        private Object record;

        public UpdateByExampleParms(Object record, QmenuExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}