package test.model;

import java.math.BigDecimal;

public class Customer {
    /**
     * This field was generated by yrtz.
     * This field corresponds to the database column qauth.CID
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    private String cid;

    /**
     * This field was generated by yrtz.
     * This field corresponds to the database column qauth.CDESC
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    private String cdesc;

    /**
     * This field was generated by yrtz.
     * This field corresponds to the database column qauth.CNAME
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    private String cname;

    /**
     * This field was generated by yrtz.
     * This field corresponds to the database column qauth.CSEQ
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    private BigDecimal cseq;

    /**
     * This field was generated by yrtz.
     * This field corresponds to the database column qauth.CURL
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    private String curl;

    /**
     * This field was generated by yrtz.
     * This field corresponds to the database column qauth.CPID
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    private String cpid;

    /**
     * This method was generated by yrtz.
     * This method returns the value of the database column qauth.CID
     *
     * @return the value of qauth.CID
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by yrtz.
     * This method sets the value of the database column qauth.CID
     *
     * @param cid the value for qauth.CID
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by yrtz.
     * This method returns the value of the database column qauth.CDESC
     *
     * @return the value of qauth.CDESC
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public String getCdesc() {
        return cdesc;
    }

    /**
     * This method was generated by yrtz.
     * This method sets the value of the database column qauth.CDESC
     *
     * @param cdesc the value for qauth.CDESC
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public void setCdesc(String cdesc) {
        this.cdesc = cdesc == null ? null : cdesc.trim();
    }

    /**
     * This method was generated by yrtz.
     * This method returns the value of the database column qauth.CNAME
     *
     * @return the value of qauth.CNAME
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by yrtz.
     * This method sets the value of the database column qauth.CNAME
     *
     * @param cname the value for qauth.CNAME
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by yrtz.
     * This method returns the value of the database column qauth.CSEQ
     *
     * @return the value of qauth.CSEQ
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public BigDecimal getCseq() {
        return cseq;
    }

    /**
     * This method was generated by yrtz.
     * This method sets the value of the database column qauth.CSEQ
     *
     * @param cseq the value for qauth.CSEQ
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public void setCseq(BigDecimal cseq) {
        this.cseq = cseq;
    }

    /**
     * This method was generated by yrtz.
     * This method returns the value of the database column qauth.CURL
     *
     * @return the value of qauth.CURL
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public String getCurl() {
        return curl;
    }

    /**
     * This method was generated by yrtz.
     * This method sets the value of the database column qauth.CURL
     *
     * @param curl the value for qauth.CURL
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public void setCurl(String curl) {
        this.curl = curl == null ? null : curl.trim();
    }

    /**
     * This method was generated by yrtz.
     * This method returns the value of the database column qauth.CPID
     *
     * @return the value of qauth.CPID
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public String getCpid() {
        return cpid;
    }

    /**
     * This method was generated by yrtz.
     * This method sets the value of the database column qauth.CPID
     *
     * @param cpid the value for qauth.CPID
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public void setCpid(String cpid) {
        this.cpid = cpid == null ? null : cpid.trim();
    }
}