package test.model;

import java.math.BigDecimal;

public class Qmenu {
    /**
     * This field was generated by yrtz.
     * This field corresponds to the database column qmenu.CID
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    private String cid;

    /**
     * This field was generated by yrtz.
     * This field corresponds to the database column qmenu.CICONCLS
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    private String ciconcls;

    /**
     * This field was generated by yrtz.
     * This field corresponds to the database column qmenu.CNAME
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    private String cname;

    /**
     * This field was generated by yrtz.
     * This field corresponds to the database column qmenu.CSEQ
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    private BigDecimal cseq;

    /**
     * This field was generated by yrtz.
     * This field corresponds to the database column qmenu.CURL
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    private String curl;

    /**
     * This field was generated by yrtz.
     * This field corresponds to the database column qmenu.CPID
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    private String cpid;

    /**
     * This method was generated by yrtz.
     * This method returns the value of the database column qmenu.CID
     *
     * @return the value of qmenu.CID
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by yrtz.
     * This method sets the value of the database column qmenu.CID
     *
     * @param cid the value for qmenu.CID
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by yrtz.
     * This method returns the value of the database column qmenu.CICONCLS
     *
     * @return the value of qmenu.CICONCLS
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public String getCiconcls() {
        return ciconcls;
    }

    /**
     * This method was generated by yrtz.
     * This method sets the value of the database column qmenu.CICONCLS
     *
     * @param ciconcls the value for qmenu.CICONCLS
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public void setCiconcls(String ciconcls) {
        this.ciconcls = ciconcls == null ? null : ciconcls.trim();
    }

    /**
     * This method was generated by yrtz.
     * This method returns the value of the database column qmenu.CNAME
     *
     * @return the value of qmenu.CNAME
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by yrtz.
     * This method sets the value of the database column qmenu.CNAME
     *
     * @param cname the value for qmenu.CNAME
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by yrtz.
     * This method returns the value of the database column qmenu.CSEQ
     *
     * @return the value of qmenu.CSEQ
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public BigDecimal getCseq() {
        return cseq;
    }

    /**
     * This method was generated by yrtz.
     * This method sets the value of the database column qmenu.CSEQ
     *
     * @param cseq the value for qmenu.CSEQ
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public void setCseq(BigDecimal cseq) {
        this.cseq = cseq;
    }

    /**
     * This method was generated by yrtz.
     * This method returns the value of the database column qmenu.CURL
     *
     * @return the value of qmenu.CURL
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public String getCurl() {
        return curl;
    }

    /**
     * This method was generated by yrtz.
     * This method sets the value of the database column qmenu.CURL
     *
     * @param curl the value for qmenu.CURL
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public void setCurl(String curl) {
        this.curl = curl == null ? null : curl.trim();
    }

    /**
     * This method was generated by yrtz.
     * This method returns the value of the database column qmenu.CPID
     *
     * @return the value of qmenu.CPID
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public String getCpid() {
        return cpid;
    }

    /**
     * This method was generated by yrtz.
     * This method sets the value of the database column qmenu.CPID
     *
     * @param cpid the value for qmenu.CPID
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public void setCpid(String cpid) {
        this.cpid = cpid == null ? null : cpid.trim();
    }
}