package test.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class QmenuExample {
    /**
     * This field was generated by yrtz.
     * This field corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    protected String orderByClause;

    /**
     * This field was generated by yrtz.
     * This field corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    protected List oredCriteria;

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public QmenuExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    protected QmenuExample(QmenuExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by yrtz.
     * This method corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by yrtz.
     * This class corresponds to the database table qmenu
     *
     * @ibatorgenerated 2015-11-27 11:44:27
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andCidIsNull() {
            addCriterion("CID is null");
            return this;
        }

        public Criteria andCidIsNotNull() {
            addCriterion("CID is not null");
            return this;
        }

        public Criteria andCidEqualTo(String value) {
            addCriterion("CID =", value, "cid");
            return this;
        }

        public Criteria andCidNotEqualTo(String value) {
            addCriterion("CID <>", value, "cid");
            return this;
        }

        public Criteria andCidGreaterThan(String value) {
            addCriterion("CID >", value, "cid");
            return this;
        }

        public Criteria andCidGreaterThanOrEqualTo(String value) {
            addCriterion("CID >=", value, "cid");
            return this;
        }

        public Criteria andCidLessThan(String value) {
            addCriterion("CID <", value, "cid");
            return this;
        }

        public Criteria andCidLessThanOrEqualTo(String value) {
            addCriterion("CID <=", value, "cid");
            return this;
        }

        public Criteria andCidLike(String value) {
            addCriterion("CID like", value, "cid");
            return this;
        }

        public Criteria andCidNotLike(String value) {
            addCriterion("CID not like", value, "cid");
            return this;
        }

        public Criteria andCidIn(List values) {
            addCriterion("CID in", values, "cid");
            return this;
        }

        public Criteria andCidNotIn(List values) {
            addCriterion("CID not in", values, "cid");
            return this;
        }

        public Criteria andCidBetween(String value1, String value2) {
            addCriterion("CID between", value1, value2, "cid");
            return this;
        }

        public Criteria andCidNotBetween(String value1, String value2) {
            addCriterion("CID not between", value1, value2, "cid");
            return this;
        }

        public Criteria andCiconclsIsNull() {
            addCriterion("CICONCLS is null");
            return this;
        }

        public Criteria andCiconclsIsNotNull() {
            addCriterion("CICONCLS is not null");
            return this;
        }

        public Criteria andCiconclsEqualTo(String value) {
            addCriterion("CICONCLS =", value, "ciconcls");
            return this;
        }

        public Criteria andCiconclsNotEqualTo(String value) {
            addCriterion("CICONCLS <>", value, "ciconcls");
            return this;
        }

        public Criteria andCiconclsGreaterThan(String value) {
            addCriterion("CICONCLS >", value, "ciconcls");
            return this;
        }

        public Criteria andCiconclsGreaterThanOrEqualTo(String value) {
            addCriterion("CICONCLS >=", value, "ciconcls");
            return this;
        }

        public Criteria andCiconclsLessThan(String value) {
            addCriterion("CICONCLS <", value, "ciconcls");
            return this;
        }

        public Criteria andCiconclsLessThanOrEqualTo(String value) {
            addCriterion("CICONCLS <=", value, "ciconcls");
            return this;
        }

        public Criteria andCiconclsLike(String value) {
            addCriterion("CICONCLS like", value, "ciconcls");
            return this;
        }

        public Criteria andCiconclsNotLike(String value) {
            addCriterion("CICONCLS not like", value, "ciconcls");
            return this;
        }

        public Criteria andCiconclsIn(List values) {
            addCriterion("CICONCLS in", values, "ciconcls");
            return this;
        }

        public Criteria andCiconclsNotIn(List values) {
            addCriterion("CICONCLS not in", values, "ciconcls");
            return this;
        }

        public Criteria andCiconclsBetween(String value1, String value2) {
            addCriterion("CICONCLS between", value1, value2, "ciconcls");
            return this;
        }

        public Criteria andCiconclsNotBetween(String value1, String value2) {
            addCriterion("CICONCLS not between", value1, value2, "ciconcls");
            return this;
        }

        public Criteria andCnameIsNull() {
            addCriterion("CNAME is null");
            return this;
        }

        public Criteria andCnameIsNotNull() {
            addCriterion("CNAME is not null");
            return this;
        }

        public Criteria andCnameEqualTo(String value) {
            addCriterion("CNAME =", value, "cname");
            return this;
        }

        public Criteria andCnameNotEqualTo(String value) {
            addCriterion("CNAME <>", value, "cname");
            return this;
        }

        public Criteria andCnameGreaterThan(String value) {
            addCriterion("CNAME >", value, "cname");
            return this;
        }

        public Criteria andCnameGreaterThanOrEqualTo(String value) {
            addCriterion("CNAME >=", value, "cname");
            return this;
        }

        public Criteria andCnameLessThan(String value) {
            addCriterion("CNAME <", value, "cname");
            return this;
        }

        public Criteria andCnameLessThanOrEqualTo(String value) {
            addCriterion("CNAME <=", value, "cname");
            return this;
        }

        public Criteria andCnameLike(String value) {
            addCriterion("CNAME like", value, "cname");
            return this;
        }

        public Criteria andCnameNotLike(String value) {
            addCriterion("CNAME not like", value, "cname");
            return this;
        }

        public Criteria andCnameIn(List values) {
            addCriterion("CNAME in", values, "cname");
            return this;
        }

        public Criteria andCnameNotIn(List values) {
            addCriterion("CNAME not in", values, "cname");
            return this;
        }

        public Criteria andCnameBetween(String value1, String value2) {
            addCriterion("CNAME between", value1, value2, "cname");
            return this;
        }

        public Criteria andCnameNotBetween(String value1, String value2) {
            addCriterion("CNAME not between", value1, value2, "cname");
            return this;
        }

        public Criteria andCseqIsNull() {
            addCriterion("CSEQ is null");
            return this;
        }

        public Criteria andCseqIsNotNull() {
            addCriterion("CSEQ is not null");
            return this;
        }

        public Criteria andCseqEqualTo(BigDecimal value) {
            addCriterion("CSEQ =", value, "cseq");
            return this;
        }

        public Criteria andCseqNotEqualTo(BigDecimal value) {
            addCriterion("CSEQ <>", value, "cseq");
            return this;
        }

        public Criteria andCseqGreaterThan(BigDecimal value) {
            addCriterion("CSEQ >", value, "cseq");
            return this;
        }

        public Criteria andCseqGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CSEQ >=", value, "cseq");
            return this;
        }

        public Criteria andCseqLessThan(BigDecimal value) {
            addCriterion("CSEQ <", value, "cseq");
            return this;
        }

        public Criteria andCseqLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CSEQ <=", value, "cseq");
            return this;
        }

        public Criteria andCseqIn(List values) {
            addCriterion("CSEQ in", values, "cseq");
            return this;
        }

        public Criteria andCseqNotIn(List values) {
            addCriterion("CSEQ not in", values, "cseq");
            return this;
        }

        public Criteria andCseqBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CSEQ between", value1, value2, "cseq");
            return this;
        }

        public Criteria andCseqNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CSEQ not between", value1, value2, "cseq");
            return this;
        }

        public Criteria andCurlIsNull() {
            addCriterion("CURL is null");
            return this;
        }

        public Criteria andCurlIsNotNull() {
            addCriterion("CURL is not null");
            return this;
        }

        public Criteria andCurlEqualTo(String value) {
            addCriterion("CURL =", value, "curl");
            return this;
        }

        public Criteria andCurlNotEqualTo(String value) {
            addCriterion("CURL <>", value, "curl");
            return this;
        }

        public Criteria andCurlGreaterThan(String value) {
            addCriterion("CURL >", value, "curl");
            return this;
        }

        public Criteria andCurlGreaterThanOrEqualTo(String value) {
            addCriterion("CURL >=", value, "curl");
            return this;
        }

        public Criteria andCurlLessThan(String value) {
            addCriterion("CURL <", value, "curl");
            return this;
        }

        public Criteria andCurlLessThanOrEqualTo(String value) {
            addCriterion("CURL <=", value, "curl");
            return this;
        }

        public Criteria andCurlLike(String value) {
            addCriterion("CURL like", value, "curl");
            return this;
        }

        public Criteria andCurlNotLike(String value) {
            addCriterion("CURL not like", value, "curl");
            return this;
        }

        public Criteria andCurlIn(List values) {
            addCriterion("CURL in", values, "curl");
            return this;
        }

        public Criteria andCurlNotIn(List values) {
            addCriterion("CURL not in", values, "curl");
            return this;
        }

        public Criteria andCurlBetween(String value1, String value2) {
            addCriterion("CURL between", value1, value2, "curl");
            return this;
        }

        public Criteria andCurlNotBetween(String value1, String value2) {
            addCriterion("CURL not between", value1, value2, "curl");
            return this;
        }

        public Criteria andCpidIsNull() {
            addCriterion("CPID is null");
            return this;
        }

        public Criteria andCpidIsNotNull() {
            addCriterion("CPID is not null");
            return this;
        }

        public Criteria andCpidEqualTo(String value) {
            addCriterion("CPID =", value, "cpid");
            return this;
        }

        public Criteria andCpidNotEqualTo(String value) {
            addCriterion("CPID <>", value, "cpid");
            return this;
        }

        public Criteria andCpidGreaterThan(String value) {
            addCriterion("CPID >", value, "cpid");
            return this;
        }

        public Criteria andCpidGreaterThanOrEqualTo(String value) {
            addCriterion("CPID >=", value, "cpid");
            return this;
        }

        public Criteria andCpidLessThan(String value) {
            addCriterion("CPID <", value, "cpid");
            return this;
        }

        public Criteria andCpidLessThanOrEqualTo(String value) {
            addCriterion("CPID <=", value, "cpid");
            return this;
        }

        public Criteria andCpidLike(String value) {
            addCriterion("CPID like", value, "cpid");
            return this;
        }

        public Criteria andCpidNotLike(String value) {
            addCriterion("CPID not like", value, "cpid");
            return this;
        }

        public Criteria andCpidIn(List values) {
            addCriterion("CPID in", values, "cpid");
            return this;
        }

        public Criteria andCpidNotIn(List values) {
            addCriterion("CPID not in", values, "cpid");
            return this;
        }

        public Criteria andCpidBetween(String value1, String value2) {
            addCriterion("CPID between", value1, value2, "cpid");
            return this;
        }

        public Criteria andCpidNotBetween(String value1, String value2) {
            addCriterion("CPID not between", value1, value2, "cpid");
            return this;
        }
    }
}