package com.wy.vas.domain;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class couponProductExample {
    /**
     * 该字段对应数据库表 coupon_product
     *
     * @ibatorgenerated 2015-12-10 23:04:49
     */
    protected String orderByClause;

    /**
     * 该字段对应数据库表 coupon_product
     *
     * @ibatorgenerated 2015-12-10 23:04:49
     */
    protected List oredCriteria;

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_product
     *
     * @ibatorgenerated 2015-12-10 23:04:49
     */
    public couponProductExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_product
     *
     * @ibatorgenerated 2015-12-10 23:04:49
     */
    protected couponProductExample(couponProductExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_product
     *
     * @ibatorgenerated 2015-12-10 23:04:49
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_product
     *
     * @ibatorgenerated 2015-12-10 23:04:49
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_product
     *
     * @ibatorgenerated 2015-12-10 23:04:49
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_product
     *
     * @ibatorgenerated 2015-12-10 23:04:49
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_product
     *
     * @ibatorgenerated 2015-12-10 23:04:49
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_product
     *
     * @ibatorgenerated 2015-12-10 23:04:49
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_product
     *
     * @ibatorgenerated 2015-12-10 23:04:49
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by yrtz.
     * 该类对应数据库表 coupon_product
     *
     * @ibatorgenerated 2015-12-10 23:04:49
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andCodeIsNull() {
            addCriterion("CODE is null");
            return this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("CODE is not null");
            return this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("CODE =", value, "code");
            return this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("CODE <>", value, "code");
            return this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("CODE >", value, "code");
            return this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CODE >=", value, "code");
            return this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("CODE <", value, "code");
            return this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("CODE <=", value, "code");
            return this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("CODE like", value, "code");
            return this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("CODE not like", value, "code");
            return this;
        }

        public Criteria andCodeIn(List values) {
            addCriterion("CODE in", values, "code");
            return this;
        }

        public Criteria andCodeNotIn(List values) {
            addCriterion("CODE not in", values, "code");
            return this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("CODE between", value1, value2, "code");
            return this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("CODE not between", value1, value2, "code");
            return this;
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("ID in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("ID not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return this;
        }

        public Criteria andProductTypeIsNull() {
            addCriterion("PRODUCT_TYPE is null");
            return this;
        }

        public Criteria andProductTypeIsNotNull() {
            addCriterion("PRODUCT_TYPE is not null");
            return this;
        }

        public Criteria andProductTypeEqualTo(Integer value) {
            addCriterion("PRODUCT_TYPE =", value, "productType");
            return this;
        }

        public Criteria andProductTypeNotEqualTo(Integer value) {
            addCriterion("PRODUCT_TYPE <>", value, "productType");
            return this;
        }

        public Criteria andProductTypeGreaterThan(Integer value) {
            addCriterion("PRODUCT_TYPE >", value, "productType");
            return this;
        }

        public Criteria andProductTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("PRODUCT_TYPE >=", value, "productType");
            return this;
        }

        public Criteria andProductTypeLessThan(Integer value) {
            addCriterion("PRODUCT_TYPE <", value, "productType");
            return this;
        }

        public Criteria andProductTypeLessThanOrEqualTo(Integer value) {
            addCriterion("PRODUCT_TYPE <=", value, "productType");
            return this;
        }

        public Criteria andProductTypeIn(List values) {
            addCriterion("PRODUCT_TYPE in", values, "productType");
            return this;
        }

        public Criteria andProductTypeNotIn(List values) {
            addCriterion("PRODUCT_TYPE not in", values, "productType");
            return this;
        }

        public Criteria andProductTypeBetween(Integer value1, Integer value2) {
            addCriterion("PRODUCT_TYPE between", value1, value2, "productType");
            return this;
        }

        public Criteria andProductTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("PRODUCT_TYPE not between", value1, value2, "productType");
            return this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("PRODUCT_NAME is null");
            return this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("PRODUCT_NAME is not null");
            return this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("PRODUCT_NAME =", value, "productName");
            return this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("PRODUCT_NAME <>", value, "productName");
            return this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("PRODUCT_NAME >", value, "productName");
            return this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCT_NAME >=", value, "productName");
            return this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("PRODUCT_NAME <", value, "productName");
            return this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("PRODUCT_NAME <=", value, "productName");
            return this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("PRODUCT_NAME like", value, "productName");
            return this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("PRODUCT_NAME not like", value, "productName");
            return this;
        }

        public Criteria andProductNameIn(List values) {
            addCriterion("PRODUCT_NAME in", values, "productName");
            return this;
        }

        public Criteria andProductNameNotIn(List values) {
            addCriterion("PRODUCT_NAME not in", values, "productName");
            return this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("PRODUCT_NAME between", value1, value2, "productName");
            return this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("PRODUCT_NAME not between", value1, value2, "productName");
            return this;
        }

        public Criteria andWorthIsNull() {
            addCriterion("WORTH is null");
            return this;
        }

        public Criteria andWorthIsNotNull() {
            addCriterion("WORTH is not null");
            return this;
        }

        public Criteria andWorthEqualTo(Double value) {
            addCriterion("WORTH =", value, "worth");
            return this;
        }

        public Criteria andWorthNotEqualTo(Double value) {
            addCriterion("WORTH <>", value, "worth");
            return this;
        }

        public Criteria andWorthGreaterThan(Double value) {
            addCriterion("WORTH >", value, "worth");
            return this;
        }

        public Criteria andWorthGreaterThanOrEqualTo(Double value) {
            addCriterion("WORTH >=", value, "worth");
            return this;
        }

        public Criteria andWorthLessThan(Double value) {
            addCriterion("WORTH <", value, "worth");
            return this;
        }

        public Criteria andWorthLessThanOrEqualTo(Double value) {
            addCriterion("WORTH <=", value, "worth");
            return this;
        }

        public Criteria andWorthIn(List values) {
            addCriterion("WORTH in", values, "worth");
            return this;
        }

        public Criteria andWorthNotIn(List values) {
            addCriterion("WORTH not in", values, "worth");
            return this;
        }

        public Criteria andWorthBetween(Double value1, Double value2) {
            addCriterion("WORTH between", value1, value2, "worth");
            return this;
        }

        public Criteria andWorthNotBetween(Double value1, Double value2) {
            addCriterion("WORTH not between", value1, value2, "worth");
            return this;
        }

        public Criteria andValidDayIsNull() {
            addCriterion("VALID_DAY is null");
            return this;
        }

        public Criteria andValidDayIsNotNull() {
            addCriterion("VALID_DAY is not null");
            return this;
        }

        public Criteria andValidDayEqualTo(Integer value) {
            addCriterion("VALID_DAY =", value, "validDay");
            return this;
        }

        public Criteria andValidDayNotEqualTo(Integer value) {
            addCriterion("VALID_DAY <>", value, "validDay");
            return this;
        }

        public Criteria andValidDayGreaterThan(Integer value) {
            addCriterion("VALID_DAY >", value, "validDay");
            return this;
        }

        public Criteria andValidDayGreaterThanOrEqualTo(Integer value) {
            addCriterion("VALID_DAY >=", value, "validDay");
            return this;
        }

        public Criteria andValidDayLessThan(Integer value) {
            addCriterion("VALID_DAY <", value, "validDay");
            return this;
        }

        public Criteria andValidDayLessThanOrEqualTo(Integer value) {
            addCriterion("VALID_DAY <=", value, "validDay");
            return this;
        }

        public Criteria andValidDayIn(List values) {
            addCriterion("VALID_DAY in", values, "validDay");
            return this;
        }

        public Criteria andValidDayNotIn(List values) {
            addCriterion("VALID_DAY not in", values, "validDay");
            return this;
        }

        public Criteria andValidDayBetween(Integer value1, Integer value2) {
            addCriterion("VALID_DAY between", value1, value2, "validDay");
            return this;
        }

        public Criteria andValidDayNotBetween(Integer value1, Integer value2) {
            addCriterion("VALID_DAY not between", value1, value2, "validDay");
            return this;
        }

        public Criteria andProducrNumberIsNull() {
            addCriterion("PRODUCR_NUMBER is null");
            return this;
        }

        public Criteria andProducrNumberIsNotNull() {
            addCriterion("PRODUCR_NUMBER is not null");
            return this;
        }

        public Criteria andProducrNumberEqualTo(Integer value) {
            addCriterion("PRODUCR_NUMBER =", value, "producrNumber");
            return this;
        }

        public Criteria andProducrNumberNotEqualTo(Integer value) {
            addCriterion("PRODUCR_NUMBER <>", value, "producrNumber");
            return this;
        }

        public Criteria andProducrNumberGreaterThan(Integer value) {
            addCriterion("PRODUCR_NUMBER >", value, "producrNumber");
            return this;
        }

        public Criteria andProducrNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("PRODUCR_NUMBER >=", value, "producrNumber");
            return this;
        }

        public Criteria andProducrNumberLessThan(Integer value) {
            addCriterion("PRODUCR_NUMBER <", value, "producrNumber");
            return this;
        }

        public Criteria andProducrNumberLessThanOrEqualTo(Integer value) {
            addCriterion("PRODUCR_NUMBER <=", value, "producrNumber");
            return this;
        }

        public Criteria andProducrNumberIn(List values) {
            addCriterion("PRODUCR_NUMBER in", values, "producrNumber");
            return this;
        }

        public Criteria andProducrNumberNotIn(List values) {
            addCriterion("PRODUCR_NUMBER not in", values, "producrNumber");
            return this;
        }

        public Criteria andProducrNumberBetween(Integer value1, Integer value2) {
            addCriterion("PRODUCR_NUMBER between", value1, value2, "producrNumber");
            return this;
        }

        public Criteria andProducrNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("PRODUCR_NUMBER not between", value1, value2, "producrNumber");
            return this;
        }

        public Criteria andProducttypeRangeIsNull() {
            addCriterion("productType_RANGE is null");
            return this;
        }

        public Criteria andProducttypeRangeIsNotNull() {
            addCriterion("productType_RANGE is not null");
            return this;
        }

        public Criteria andProducttypeRangeEqualTo(String value) {
            addCriterion("productType_RANGE =", value, "producttypeRange");
            return this;
        }

        public Criteria andProducttypeRangeNotEqualTo(String value) {
            addCriterion("productType_RANGE <>", value, "producttypeRange");
            return this;
        }

        public Criteria andProducttypeRangeGreaterThan(String value) {
            addCriterion("productType_RANGE >", value, "producttypeRange");
            return this;
        }

        public Criteria andProducttypeRangeGreaterThanOrEqualTo(String value) {
            addCriterion("productType_RANGE >=", value, "producttypeRange");
            return this;
        }

        public Criteria andProducttypeRangeLessThan(String value) {
            addCriterion("productType_RANGE <", value, "producttypeRange");
            return this;
        }

        public Criteria andProducttypeRangeLessThanOrEqualTo(String value) {
            addCriterion("productType_RANGE <=", value, "producttypeRange");
            return this;
        }

        public Criteria andProducttypeRangeLike(String value) {
            addCriterion("productType_RANGE like", value, "producttypeRange");
            return this;
        }

        public Criteria andProducttypeRangeNotLike(String value) {
            addCriterion("productType_RANGE not like", value, "producttypeRange");
            return this;
        }

        public Criteria andProducttypeRangeIn(List values) {
            addCriterion("productType_RANGE in", values, "producttypeRange");
            return this;
        }

        public Criteria andProducttypeRangeNotIn(List values) {
            addCriterion("productType_RANGE not in", values, "producttypeRange");
            return this;
        }

        public Criteria andProducttypeRangeBetween(String value1, String value2) {
            addCriterion("productType_RANGE between", value1, value2, "producttypeRange");
            return this;
        }

        public Criteria andProducttypeRangeNotBetween(String value1, String value2) {
            addCriterion("productType_RANGE not between", value1, value2, "producttypeRange");
            return this;
        }

        public Criteria andAmountMinIsNull() {
            addCriterion("AMOUNT_MIN is null");
            return this;
        }

        public Criteria andAmountMinIsNotNull() {
            addCriterion("AMOUNT_MIN is not null");
            return this;
        }

        public Criteria andAmountMinEqualTo(Double value) {
            addCriterion("AMOUNT_MIN =", value, "amountMin");
            return this;
        }

        public Criteria andAmountMinNotEqualTo(Double value) {
            addCriterion("AMOUNT_MIN <>", value, "amountMin");
            return this;
        }

        public Criteria andAmountMinGreaterThan(Double value) {
            addCriterion("AMOUNT_MIN >", value, "amountMin");
            return this;
        }

        public Criteria andAmountMinGreaterThanOrEqualTo(Double value) {
            addCriterion("AMOUNT_MIN >=", value, "amountMin");
            return this;
        }

        public Criteria andAmountMinLessThan(Double value) {
            addCriterion("AMOUNT_MIN <", value, "amountMin");
            return this;
        }

        public Criteria andAmountMinLessThanOrEqualTo(Double value) {
            addCriterion("AMOUNT_MIN <=", value, "amountMin");
            return this;
        }

        public Criteria andAmountMinIn(List values) {
            addCriterion("AMOUNT_MIN in", values, "amountMin");
            return this;
        }

        public Criteria andAmountMinNotIn(List values) {
            addCriterion("AMOUNT_MIN not in", values, "amountMin");
            return this;
        }

        public Criteria andAmountMinBetween(Double value1, Double value2) {
            addCriterion("AMOUNT_MIN between", value1, value2, "amountMin");
            return this;
        }

        public Criteria andAmountMinNotBetween(Double value1, Double value2) {
            addCriterion("AMOUNT_MIN not between", value1, value2, "amountMin");
            return this;
        }

        public Criteria andAmountMaxIsNull() {
            addCriterion("AMOUNT_MAX is null");
            return this;
        }

        public Criteria andAmountMaxIsNotNull() {
            addCriterion("AMOUNT_MAX is not null");
            return this;
        }

        public Criteria andAmountMaxEqualTo(Double value) {
            addCriterion("AMOUNT_MAX =", value, "amountMax");
            return this;
        }

        public Criteria andAmountMaxNotEqualTo(Double value) {
            addCriterion("AMOUNT_MAX <>", value, "amountMax");
            return this;
        }

        public Criteria andAmountMaxGreaterThan(Double value) {
            addCriterion("AMOUNT_MAX >", value, "amountMax");
            return this;
        }

        public Criteria andAmountMaxGreaterThanOrEqualTo(Double value) {
            addCriterion("AMOUNT_MAX >=", value, "amountMax");
            return this;
        }

        public Criteria andAmountMaxLessThan(Double value) {
            addCriterion("AMOUNT_MAX <", value, "amountMax");
            return this;
        }

        public Criteria andAmountMaxLessThanOrEqualTo(Double value) {
            addCriterion("AMOUNT_MAX <=", value, "amountMax");
            return this;
        }

        public Criteria andAmountMaxIn(List values) {
            addCriterion("AMOUNT_MAX in", values, "amountMax");
            return this;
        }

        public Criteria andAmountMaxNotIn(List values) {
            addCriterion("AMOUNT_MAX not in", values, "amountMax");
            return this;
        }

        public Criteria andAmountMaxBetween(Double value1, Double value2) {
            addCriterion("AMOUNT_MAX between", value1, value2, "amountMax");
            return this;
        }

        public Criteria andAmountMaxNotBetween(Double value1, Double value2) {
            addCriterion("AMOUNT_MAX not between", value1, value2, "amountMax");
            return this;
        }

        public Criteria andIsOpenIsNull() {
            addCriterion("IS_OPEN is null");
            return this;
        }

        public Criteria andIsOpenIsNotNull() {
            addCriterion("IS_OPEN is not null");
            return this;
        }

        public Criteria andIsOpenEqualTo(Integer value) {
            addCriterion("IS_OPEN =", value, "isOpen");
            return this;
        }

        public Criteria andIsOpenNotEqualTo(Integer value) {
            addCriterion("IS_OPEN <>", value, "isOpen");
            return this;
        }

        public Criteria andIsOpenGreaterThan(Integer value) {
            addCriterion("IS_OPEN >", value, "isOpen");
            return this;
        }

        public Criteria andIsOpenGreaterThanOrEqualTo(Integer value) {
            addCriterion("IS_OPEN >=", value, "isOpen");
            return this;
        }

        public Criteria andIsOpenLessThan(Integer value) {
            addCriterion("IS_OPEN <", value, "isOpen");
            return this;
        }

        public Criteria andIsOpenLessThanOrEqualTo(Integer value) {
            addCriterion("IS_OPEN <=", value, "isOpen");
            return this;
        }

        public Criteria andIsOpenIn(List values) {
            addCriterion("IS_OPEN in", values, "isOpen");
            return this;
        }

        public Criteria andIsOpenNotIn(List values) {
            addCriterion("IS_OPEN not in", values, "isOpen");
            return this;
        }

        public Criteria andIsOpenBetween(Integer value1, Integer value2) {
            addCriterion("IS_OPEN between", value1, value2, "isOpen");
            return this;
        }

        public Criteria andIsOpenNotBetween(Integer value1, Integer value2) {
            addCriterion("IS_OPEN not between", value1, value2, "isOpen");
            return this;
        }

        public Criteria andIsCreateIsNull() {
            addCriterion("IS_CREATE is null");
            return this;
        }

        public Criteria andIsCreateIsNotNull() {
            addCriterion("IS_CREATE is not null");
            return this;
        }

        public Criteria andIsCreateEqualTo(Integer value) {
            addCriterion("IS_CREATE =", value, "isCreate");
            return this;
        }

        public Criteria andIsCreateNotEqualTo(Integer value) {
            addCriterion("IS_CREATE <>", value, "isCreate");
            return this;
        }

        public Criteria andIsCreateGreaterThan(Integer value) {
            addCriterion("IS_CREATE >", value, "isCreate");
            return this;
        }

        public Criteria andIsCreateGreaterThanOrEqualTo(Integer value) {
            addCriterion("IS_CREATE >=", value, "isCreate");
            return this;
        }

        public Criteria andIsCreateLessThan(Integer value) {
            addCriterion("IS_CREATE <", value, "isCreate");
            return this;
        }

        public Criteria andIsCreateLessThanOrEqualTo(Integer value) {
            addCriterion("IS_CREATE <=", value, "isCreate");
            return this;
        }

        public Criteria andIsCreateIn(List values) {
            addCriterion("IS_CREATE in", values, "isCreate");
            return this;
        }

        public Criteria andIsCreateNotIn(List values) {
            addCriterion("IS_CREATE not in", values, "isCreate");
            return this;
        }

        public Criteria andIsCreateBetween(Integer value1, Integer value2) {
            addCriterion("IS_CREATE between", value1, value2, "isCreate");
            return this;
        }

        public Criteria andIsCreateNotBetween(Integer value1, Integer value2) {
            addCriterion("IS_CREATE not between", value1, value2, "isCreate");
            return this;
        }

        public Criteria andModifyUsercodeIsNull() {
            addCriterion("MODIFY_USERCODE is null");
            return this;
        }

        public Criteria andModifyUsercodeIsNotNull() {
            addCriterion("MODIFY_USERCODE is not null");
            return this;
        }

        public Criteria andModifyUsercodeEqualTo(String value) {
            addCriterion("MODIFY_USERCODE =", value, "modifyUsercode");
            return this;
        }

        public Criteria andModifyUsercodeNotEqualTo(String value) {
            addCriterion("MODIFY_USERCODE <>", value, "modifyUsercode");
            return this;
        }

        public Criteria andModifyUsercodeGreaterThan(String value) {
            addCriterion("MODIFY_USERCODE >", value, "modifyUsercode");
            return this;
        }

        public Criteria andModifyUsercodeGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFY_USERCODE >=", value, "modifyUsercode");
            return this;
        }

        public Criteria andModifyUsercodeLessThan(String value) {
            addCriterion("MODIFY_USERCODE <", value, "modifyUsercode");
            return this;
        }

        public Criteria andModifyUsercodeLessThanOrEqualTo(String value) {
            addCriterion("MODIFY_USERCODE <=", value, "modifyUsercode");
            return this;
        }

        public Criteria andModifyUsercodeLike(String value) {
            addCriterion("MODIFY_USERCODE like", value, "modifyUsercode");
            return this;
        }

        public Criteria andModifyUsercodeNotLike(String value) {
            addCriterion("MODIFY_USERCODE not like", value, "modifyUsercode");
            return this;
        }

        public Criteria andModifyUsercodeIn(List values) {
            addCriterion("MODIFY_USERCODE in", values, "modifyUsercode");
            return this;
        }

        public Criteria andModifyUsercodeNotIn(List values) {
            addCriterion("MODIFY_USERCODE not in", values, "modifyUsercode");
            return this;
        }

        public Criteria andModifyUsercodeBetween(String value1, String value2) {
            addCriterion("MODIFY_USERCODE between", value1, value2, "modifyUsercode");
            return this;
        }

        public Criteria andModifyUsercodeNotBetween(String value1, String value2) {
            addCriterion("MODIFY_USERCODE not between", value1, value2, "modifyUsercode");
            return this;
        }

        public Criteria andModifyUsernameIsNull() {
            addCriterion("MODIFY_USERNAME is null");
            return this;
        }

        public Criteria andModifyUsernameIsNotNull() {
            addCriterion("MODIFY_USERNAME is not null");
            return this;
        }

        public Criteria andModifyUsernameEqualTo(String value) {
            addCriterion("MODIFY_USERNAME =", value, "modifyUsername");
            return this;
        }

        public Criteria andModifyUsernameNotEqualTo(String value) {
            addCriterion("MODIFY_USERNAME <>", value, "modifyUsername");
            return this;
        }

        public Criteria andModifyUsernameGreaterThan(String value) {
            addCriterion("MODIFY_USERNAME >", value, "modifyUsername");
            return this;
        }

        public Criteria andModifyUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFY_USERNAME >=", value, "modifyUsername");
            return this;
        }

        public Criteria andModifyUsernameLessThan(String value) {
            addCriterion("MODIFY_USERNAME <", value, "modifyUsername");
            return this;
        }

        public Criteria andModifyUsernameLessThanOrEqualTo(String value) {
            addCriterion("MODIFY_USERNAME <=", value, "modifyUsername");
            return this;
        }

        public Criteria andModifyUsernameLike(String value) {
            addCriterion("MODIFY_USERNAME like", value, "modifyUsername");
            return this;
        }

        public Criteria andModifyUsernameNotLike(String value) {
            addCriterion("MODIFY_USERNAME not like", value, "modifyUsername");
            return this;
        }

        public Criteria andModifyUsernameIn(List values) {
            addCriterion("MODIFY_USERNAME in", values, "modifyUsername");
            return this;
        }

        public Criteria andModifyUsernameNotIn(List values) {
            addCriterion("MODIFY_USERNAME not in", values, "modifyUsername");
            return this;
        }

        public Criteria andModifyUsernameBetween(String value1, String value2) {
            addCriterion("MODIFY_USERNAME between", value1, value2, "modifyUsername");
            return this;
        }

        public Criteria andModifyUsernameNotBetween(String value1, String value2) {
            addCriterion("MODIFY_USERNAME not between", value1, value2, "modifyUsername");
            return this;
        }
    }
}