package com.wy.vas.domain;

public class CouponDetailCondition {
    /**
     * 该字段对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    protected String orderByClause;

    /**
     * 该字段对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    protected List oredCriteria;

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    public CouponDetailCondition() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    protected CouponDetailCondition(CouponDetailCondition example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }
}