package com.wy.vas.domain;

import com.wy.domain.persistence.BaseInfo;
import java.util.Date;

public class CouponDetail extends BaseInfo {
    /**
     * 该字段对应数据库列 coupon_detail.CODE
     *
     * @ibatorgenerated
     */
    private String code;

    /**
     * 该字段对应数据库列 coupon_detail.ID
     *
     * @ibatorgenerated
     */
    private Integer id;

    /**
     * 该字段对应数据库列 coupon_detail.USER_CODE
     *
     * @ibatorgenerated
     */
    private String userCode;

    /**
     * 该字段对应数据库列 coupon_detail.COUPON_PRODUCT_CODE
     *
     * @ibatorgenerated
     */
    private String couponProductCode;

    /**
     * 该字段对应数据库列 coupon_detail.AVT_KEY
     *
     * @ibatorgenerated
     */
    private String avtKey;

    /**
     * 该字段对应数据库列 coupon_detail.STATE
     *
     * @ibatorgenerated
     */
    private Integer state;

    /**
     * 该字段对应数据库列 coupon_detail.USED_TIME
     *
     * @ibatorgenerated
     */
    private Date usedTime;

    /**
     * 该字段对应数据库列 coupon_detail.TEL
     *
     * @ibatorgenerated
     */
    private String tel;

    /**
     * 该字段对应数据库列 coupon_detail.SOURCE_CODE
     *
     * @ibatorgenerated
     */
    private String sourceCode;

    /**
     * 该字段对应数据库列 coupon_detail.SOURCE_TYPE
     *
     * @ibatorgenerated
     */
    private Integer sourceType;

    /**
     * 该字段对应数据库列 coupon_detail.CREATE_USER
     *
     * @ibatorgenerated
     */
    private String createUser;

    /**
     * 该字段对应数据库列 coupon_detail.CREATE_USERNAME
     *
     * @ibatorgenerated
     */
    private String createUsername;

    /**
     * 该字段对应数据库列 coupon_detail.CREATE_TIME
     *
     * @ibatorgenerated
     */
    private String createTime;

    /**
     * 该字段对应数据库列 coupon_detail.MODIFY_USERCODE
     *
     * @ibatorgenerated
     */
    private String modifyUsercode;

    /**
     * 该字段对应数据库列 coupon_detail.MODIFY_USERNAME
     *
     * @ibatorgenerated
     */
    private String modifyUsername;

    /**
     * 该字段对应数据库列 coupon_detail.MODIFY_TIME
     *
     * @ibatorgenerated
     */
    private Date modifyTime;

    /**
     * This method was generated by yrtz.
     * 返回数据库列 coupon_detail.CODE 的值
     *
     * @return 列  coupon_detail.CODE 的值
     *
     * @ibatorgenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by yrtz.
     * 设置数据库列 coupon_detail.CODE 的值
     *
     * @param code the value for coupon_detail.CODE
     *
     * @ibatorgenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by yrtz.
     * 返回数据库列 coupon_detail.ID 的值
     *
     * @return 列  coupon_detail.ID 的值
     *
     * @ibatorgenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by yrtz.
     * 设置数据库列 coupon_detail.ID 的值
     *
     * @param id the value for coupon_detail.ID
     *
     * @ibatorgenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by yrtz.
     * 返回数据库列 coupon_detail.USER_CODE 的值
     *
     * @return 列  coupon_detail.USER_CODE 的值
     *
     * @ibatorgenerated
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by yrtz.
     * 设置数据库列 coupon_detail.USER_CODE 的值
     *
     * @param userCode the value for coupon_detail.USER_CODE
     *
     * @ibatorgenerated
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by yrtz.
     * 返回数据库列 coupon_detail.COUPON_PRODUCT_CODE 的值
     *
     * @return 列  coupon_detail.COUPON_PRODUCT_CODE 的值
     *
     * @ibatorgenerated
     */
    public String getCouponProductCode() {
        return couponProductCode;
    }

    /**
     * This method was generated by yrtz.
     * 设置数据库列 coupon_detail.COUPON_PRODUCT_CODE 的值
     *
     * @param couponProductCode the value for coupon_detail.COUPON_PRODUCT_CODE
     *
     * @ibatorgenerated
     */
    public void setCouponProductCode(String couponProductCode) {
        this.couponProductCode = couponProductCode == null ? null : couponProductCode.trim();
    }

    /**
     * This method was generated by yrtz.
     * 返回数据库列 coupon_detail.AVT_KEY 的值
     *
     * @return 列  coupon_detail.AVT_KEY 的值
     *
     * @ibatorgenerated
     */
    public String getAvtKey() {
        return avtKey;
    }

    /**
     * This method was generated by yrtz.
     * 设置数据库列 coupon_detail.AVT_KEY 的值
     *
     * @param avtKey the value for coupon_detail.AVT_KEY
     *
     * @ibatorgenerated
     */
    public void setAvtKey(String avtKey) {
        this.avtKey = avtKey == null ? null : avtKey.trim();
    }

    /**
     * This method was generated by yrtz.
     * 返回数据库列 coupon_detail.STATE 的值
     *
     * @return 列  coupon_detail.STATE 的值
     *
     * @ibatorgenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by yrtz.
     * 设置数据库列 coupon_detail.STATE 的值
     *
     * @param state the value for coupon_detail.STATE
     *
     * @ibatorgenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by yrtz.
     * 返回数据库列 coupon_detail.USED_TIME 的值
     *
     * @return 列  coupon_detail.USED_TIME 的值
     *
     * @ibatorgenerated
     */
    public Date getUsedTime() {
        return usedTime;
    }

    /**
     * This method was generated by yrtz.
     * 设置数据库列 coupon_detail.USED_TIME 的值
     *
     * @param usedTime the value for coupon_detail.USED_TIME
     *
     * @ibatorgenerated
     */
    public void setUsedTime(Date usedTime) {
        this.usedTime = usedTime;
    }

    /**
     * This method was generated by yrtz.
     * 返回数据库列 coupon_detail.TEL 的值
     *
     * @return 列  coupon_detail.TEL 的值
     *
     * @ibatorgenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by yrtz.
     * 设置数据库列 coupon_detail.TEL 的值
     *
     * @param tel the value for coupon_detail.TEL
     *
     * @ibatorgenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by yrtz.
     * 返回数据库列 coupon_detail.SOURCE_CODE 的值
     *
     * @return 列  coupon_detail.SOURCE_CODE 的值
     *
     * @ibatorgenerated
     */
    public String getSourceCode() {
        return sourceCode;
    }

    /**
     * This method was generated by yrtz.
     * 设置数据库列 coupon_detail.SOURCE_CODE 的值
     *
     * @param sourceCode the value for coupon_detail.SOURCE_CODE
     *
     * @ibatorgenerated
     */
    public void setSourceCode(String sourceCode) {
        this.sourceCode = sourceCode == null ? null : sourceCode.trim();
    }

    /**
     * This method was generated by yrtz.
     * 返回数据库列 coupon_detail.SOURCE_TYPE 的值
     *
     * @return 列  coupon_detail.SOURCE_TYPE 的值
     *
     * @ibatorgenerated
     */
    public Integer getSourceType() {
        return sourceType;
    }

    /**
     * This method was generated by yrtz.
     * 设置数据库列 coupon_detail.SOURCE_TYPE 的值
     *
     * @param sourceType the value for coupon_detail.SOURCE_TYPE
     *
     * @ibatorgenerated
     */
    public void setSourceType(Integer sourceType) {
        this.sourceType = sourceType;
    }

    /**
     * This method was generated by yrtz.
     * 返回数据库列 coupon_detail.CREATE_USER 的值
     *
     * @return 列  coupon_detail.CREATE_USER 的值
     *
     * @ibatorgenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by yrtz.
     * 设置数据库列 coupon_detail.CREATE_USER 的值
     *
     * @param createUser the value for coupon_detail.CREATE_USER
     *
     * @ibatorgenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by yrtz.
     * 返回数据库列 coupon_detail.CREATE_USERNAME 的值
     *
     * @return 列  coupon_detail.CREATE_USERNAME 的值
     *
     * @ibatorgenerated
     */
    public String getCreateUsername() {
        return createUsername;
    }

    /**
     * This method was generated by yrtz.
     * 设置数据库列 coupon_detail.CREATE_USERNAME 的值
     *
     * @param createUsername the value for coupon_detail.CREATE_USERNAME
     *
     * @ibatorgenerated
     */
    public void setCreateUsername(String createUsername) {
        this.createUsername = createUsername == null ? null : createUsername.trim();
    }

    /**
     * This method was generated by yrtz.
     * 返回数据库列 coupon_detail.CREATE_TIME 的值
     *
     * @return 列  coupon_detail.CREATE_TIME 的值
     *
     * @ibatorgenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by yrtz.
     * 设置数据库列 coupon_detail.CREATE_TIME 的值
     *
     * @param createTime the value for coupon_detail.CREATE_TIME
     *
     * @ibatorgenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by yrtz.
     * 返回数据库列 coupon_detail.MODIFY_USERCODE 的值
     *
     * @return 列  coupon_detail.MODIFY_USERCODE 的值
     *
     * @ibatorgenerated
     */
    public String getModifyUsercode() {
        return modifyUsercode;
    }

    /**
     * This method was generated by yrtz.
     * 设置数据库列 coupon_detail.MODIFY_USERCODE 的值
     *
     * @param modifyUsercode the value for coupon_detail.MODIFY_USERCODE
     *
     * @ibatorgenerated
     */
    public void setModifyUsercode(String modifyUsercode) {
        this.modifyUsercode = modifyUsercode == null ? null : modifyUsercode.trim();
    }

    /**
     * This method was generated by yrtz.
     * 返回数据库列 coupon_detail.MODIFY_USERNAME 的值
     *
     * @return 列  coupon_detail.MODIFY_USERNAME 的值
     *
     * @ibatorgenerated
     */
    public String getModifyUsername() {
        return modifyUsername;
    }

    /**
     * This method was generated by yrtz.
     * 设置数据库列 coupon_detail.MODIFY_USERNAME 的值
     *
     * @param modifyUsername the value for coupon_detail.MODIFY_USERNAME
     *
     * @ibatorgenerated
     */
    public void setModifyUsername(String modifyUsername) {
        this.modifyUsername = modifyUsername == null ? null : modifyUsername.trim();
    }

    /**
     * This method was generated by yrtz.
     * 返回数据库列 coupon_detail.MODIFY_TIME 的值
     *
     * @return 列  coupon_detail.MODIFY_TIME 的值
     *
     * @ibatorgenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by yrtz.
     * 设置数据库列 coupon_detail.MODIFY_TIME 的值
     *
     * @param modifyTime the value for coupon_detail.MODIFY_TIME
     *
     * @ibatorgenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}