package com.wy.vas.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CouponDetailExample {
    /**
     * 该字段对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    protected String orderByClause;

    /**
     * 该字段对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    protected List oredCriteria;

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    public CouponDetailExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    protected CouponDetailExample(CouponDetailExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by yrtz.
     * 该方法对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by yrtz.
     * 该类对应数据库表 coupon_detail
     *
     * @ibatorgenerated
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andCodeIsNull() {
            addCriterion("CODE is null");
            return this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("CODE is not null");
            return this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("CODE =", value, "code");
            return this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("CODE <>", value, "code");
            return this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("CODE >", value, "code");
            return this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CODE >=", value, "code");
            return this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("CODE <", value, "code");
            return this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("CODE <=", value, "code");
            return this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("CODE like", value, "code");
            return this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("CODE not like", value, "code");
            return this;
        }

        public Criteria andCodeIn(List values) {
            addCriterion("CODE in", values, "code");
            return this;
        }

        public Criteria andCodeNotIn(List values) {
            addCriterion("CODE not in", values, "code");
            return this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("CODE between", value1, value2, "code");
            return this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("CODE not between", value1, value2, "code");
            return this;
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List values) {
            addCriterion("ID in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List values) {
            addCriterion("ID not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return this;
        }

        public Criteria andUserCodeIsNull() {
            addCriterion("USER_CODE is null");
            return this;
        }

        public Criteria andUserCodeIsNotNull() {
            addCriterion("USER_CODE is not null");
            return this;
        }

        public Criteria andUserCodeEqualTo(String value) {
            addCriterion("USER_CODE =", value, "userCode");
            return this;
        }

        public Criteria andUserCodeNotEqualTo(String value) {
            addCriterion("USER_CODE <>", value, "userCode");
            return this;
        }

        public Criteria andUserCodeGreaterThan(String value) {
            addCriterion("USER_CODE >", value, "userCode");
            return this;
        }

        public Criteria andUserCodeGreaterThanOrEqualTo(String value) {
            addCriterion("USER_CODE >=", value, "userCode");
            return this;
        }

        public Criteria andUserCodeLessThan(String value) {
            addCriterion("USER_CODE <", value, "userCode");
            return this;
        }

        public Criteria andUserCodeLessThanOrEqualTo(String value) {
            addCriterion("USER_CODE <=", value, "userCode");
            return this;
        }

        public Criteria andUserCodeLike(String value) {
            addCriterion("USER_CODE like", value, "userCode");
            return this;
        }

        public Criteria andUserCodeNotLike(String value) {
            addCriterion("USER_CODE not like", value, "userCode");
            return this;
        }

        public Criteria andUserCodeIn(List values) {
            addCriterion("USER_CODE in", values, "userCode");
            return this;
        }

        public Criteria andUserCodeNotIn(List values) {
            addCriterion("USER_CODE not in", values, "userCode");
            return this;
        }

        public Criteria andUserCodeBetween(String value1, String value2) {
            addCriterion("USER_CODE between", value1, value2, "userCode");
            return this;
        }

        public Criteria andUserCodeNotBetween(String value1, String value2) {
            addCriterion("USER_CODE not between", value1, value2, "userCode");
            return this;
        }

        public Criteria andCouponProductCodeIsNull() {
            addCriterion("COUPON_PRODUCT_CODE is null");
            return this;
        }

        public Criteria andCouponProductCodeIsNotNull() {
            addCriterion("COUPON_PRODUCT_CODE is not null");
            return this;
        }

        public Criteria andCouponProductCodeEqualTo(String value) {
            addCriterion("COUPON_PRODUCT_CODE =", value, "couponProductCode");
            return this;
        }

        public Criteria andCouponProductCodeNotEqualTo(String value) {
            addCriterion("COUPON_PRODUCT_CODE <>", value, "couponProductCode");
            return this;
        }

        public Criteria andCouponProductCodeGreaterThan(String value) {
            addCriterion("COUPON_PRODUCT_CODE >", value, "couponProductCode");
            return this;
        }

        public Criteria andCouponProductCodeGreaterThanOrEqualTo(String value) {
            addCriterion("COUPON_PRODUCT_CODE >=", value, "couponProductCode");
            return this;
        }

        public Criteria andCouponProductCodeLessThan(String value) {
            addCriterion("COUPON_PRODUCT_CODE <", value, "couponProductCode");
            return this;
        }

        public Criteria andCouponProductCodeLessThanOrEqualTo(String value) {
            addCriterion("COUPON_PRODUCT_CODE <=", value, "couponProductCode");
            return this;
        }

        public Criteria andCouponProductCodeLike(String value) {
            addCriterion("COUPON_PRODUCT_CODE like", value, "couponProductCode");
            return this;
        }

        public Criteria andCouponProductCodeNotLike(String value) {
            addCriterion("COUPON_PRODUCT_CODE not like", value, "couponProductCode");
            return this;
        }

        public Criteria andCouponProductCodeIn(List values) {
            addCriterion("COUPON_PRODUCT_CODE in", values, "couponProductCode");
            return this;
        }

        public Criteria andCouponProductCodeNotIn(List values) {
            addCriterion("COUPON_PRODUCT_CODE not in", values, "couponProductCode");
            return this;
        }

        public Criteria andCouponProductCodeBetween(String value1, String value2) {
            addCriterion("COUPON_PRODUCT_CODE between", value1, value2, "couponProductCode");
            return this;
        }

        public Criteria andCouponProductCodeNotBetween(String value1, String value2) {
            addCriterion("COUPON_PRODUCT_CODE not between", value1, value2, "couponProductCode");
            return this;
        }

        public Criteria andAvtKeyIsNull() {
            addCriterion("AVT_KEY is null");
            return this;
        }

        public Criteria andAvtKeyIsNotNull() {
            addCriterion("AVT_KEY is not null");
            return this;
        }

        public Criteria andAvtKeyEqualTo(String value) {
            addCriterion("AVT_KEY =", value, "avtKey");
            return this;
        }

        public Criteria andAvtKeyNotEqualTo(String value) {
            addCriterion("AVT_KEY <>", value, "avtKey");
            return this;
        }

        public Criteria andAvtKeyGreaterThan(String value) {
            addCriterion("AVT_KEY >", value, "avtKey");
            return this;
        }

        public Criteria andAvtKeyGreaterThanOrEqualTo(String value) {
            addCriterion("AVT_KEY >=", value, "avtKey");
            return this;
        }

        public Criteria andAvtKeyLessThan(String value) {
            addCriterion("AVT_KEY <", value, "avtKey");
            return this;
        }

        public Criteria andAvtKeyLessThanOrEqualTo(String value) {
            addCriterion("AVT_KEY <=", value, "avtKey");
            return this;
        }

        public Criteria andAvtKeyLike(String value) {
            addCriterion("AVT_KEY like", value, "avtKey");
            return this;
        }

        public Criteria andAvtKeyNotLike(String value) {
            addCriterion("AVT_KEY not like", value, "avtKey");
            return this;
        }

        public Criteria andAvtKeyIn(List values) {
            addCriterion("AVT_KEY in", values, "avtKey");
            return this;
        }

        public Criteria andAvtKeyNotIn(List values) {
            addCriterion("AVT_KEY not in", values, "avtKey");
            return this;
        }

        public Criteria andAvtKeyBetween(String value1, String value2) {
            addCriterion("AVT_KEY between", value1, value2, "avtKey");
            return this;
        }

        public Criteria andAvtKeyNotBetween(String value1, String value2) {
            addCriterion("AVT_KEY not between", value1, value2, "avtKey");
            return this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE is null");
            return this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE is not null");
            return this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("STATE =", value, "state");
            return this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("STATE <>", value, "state");
            return this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("STATE >", value, "state");
            return this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("STATE >=", value, "state");
            return this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("STATE <", value, "state");
            return this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("STATE <=", value, "state");
            return this;
        }

        public Criteria andStateIn(List values) {
            addCriterion("STATE in", values, "state");
            return this;
        }

        public Criteria andStateNotIn(List values) {
            addCriterion("STATE not in", values, "state");
            return this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("STATE between", value1, value2, "state");
            return this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("STATE not between", value1, value2, "state");
            return this;
        }

        public Criteria andUsedTimeIsNull() {
            addCriterion("USED_TIME is null");
            return this;
        }

        public Criteria andUsedTimeIsNotNull() {
            addCriterion("USED_TIME is not null");
            return this;
        }

        public Criteria andUsedTimeEqualTo(Date value) {
            addCriterion("USED_TIME =", value, "usedTime");
            return this;
        }

        public Criteria andUsedTimeNotEqualTo(Date value) {
            addCriterion("USED_TIME <>", value, "usedTime");
            return this;
        }

        public Criteria andUsedTimeGreaterThan(Date value) {
            addCriterion("USED_TIME >", value, "usedTime");
            return this;
        }

        public Criteria andUsedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("USED_TIME >=", value, "usedTime");
            return this;
        }

        public Criteria andUsedTimeLessThan(Date value) {
            addCriterion("USED_TIME <", value, "usedTime");
            return this;
        }

        public Criteria andUsedTimeLessThanOrEqualTo(Date value) {
            addCriterion("USED_TIME <=", value, "usedTime");
            return this;
        }

        public Criteria andUsedTimeIn(List values) {
            addCriterion("USED_TIME in", values, "usedTime");
            return this;
        }

        public Criteria andUsedTimeNotIn(List values) {
            addCriterion("USED_TIME not in", values, "usedTime");
            return this;
        }

        public Criteria andUsedTimeBetween(Date value1, Date value2) {
            addCriterion("USED_TIME between", value1, value2, "usedTime");
            return this;
        }

        public Criteria andUsedTimeNotBetween(Date value1, Date value2) {
            addCriterion("USED_TIME not between", value1, value2, "usedTime");
            return this;
        }

        public Criteria andTelIsNull() {
            addCriterion("TEL is null");
            return this;
        }

        public Criteria andTelIsNotNull() {
            addCriterion("TEL is not null");
            return this;
        }

        public Criteria andTelEqualTo(String value) {
            addCriterion("TEL =", value, "tel");
            return this;
        }

        public Criteria andTelNotEqualTo(String value) {
            addCriterion("TEL <>", value, "tel");
            return this;
        }

        public Criteria andTelGreaterThan(String value) {
            addCriterion("TEL >", value, "tel");
            return this;
        }

        public Criteria andTelGreaterThanOrEqualTo(String value) {
            addCriterion("TEL >=", value, "tel");
            return this;
        }

        public Criteria andTelLessThan(String value) {
            addCriterion("TEL <", value, "tel");
            return this;
        }

        public Criteria andTelLessThanOrEqualTo(String value) {
            addCriterion("TEL <=", value, "tel");
            return this;
        }

        public Criteria andTelLike(String value) {
            addCriterion("TEL like", value, "tel");
            return this;
        }

        public Criteria andTelNotLike(String value) {
            addCriterion("TEL not like", value, "tel");
            return this;
        }

        public Criteria andTelIn(List values) {
            addCriterion("TEL in", values, "tel");
            return this;
        }

        public Criteria andTelNotIn(List values) {
            addCriterion("TEL not in", values, "tel");
            return this;
        }

        public Criteria andTelBetween(String value1, String value2) {
            addCriterion("TEL between", value1, value2, "tel");
            return this;
        }

        public Criteria andTelNotBetween(String value1, String value2) {
            addCriterion("TEL not between", value1, value2, "tel");
            return this;
        }

        public Criteria andSourceCodeIsNull() {
            addCriterion("SOURCE_CODE is null");
            return this;
        }

        public Criteria andSourceCodeIsNotNull() {
            addCriterion("SOURCE_CODE is not null");
            return this;
        }

        public Criteria andSourceCodeEqualTo(String value) {
            addCriterion("SOURCE_CODE =", value, "sourceCode");
            return this;
        }

        public Criteria andSourceCodeNotEqualTo(String value) {
            addCriterion("SOURCE_CODE <>", value, "sourceCode");
            return this;
        }

        public Criteria andSourceCodeGreaterThan(String value) {
            addCriterion("SOURCE_CODE >", value, "sourceCode");
            return this;
        }

        public Criteria andSourceCodeGreaterThanOrEqualTo(String value) {
            addCriterion("SOURCE_CODE >=", value, "sourceCode");
            return this;
        }

        public Criteria andSourceCodeLessThan(String value) {
            addCriterion("SOURCE_CODE <", value, "sourceCode");
            return this;
        }

        public Criteria andSourceCodeLessThanOrEqualTo(String value) {
            addCriterion("SOURCE_CODE <=", value, "sourceCode");
            return this;
        }

        public Criteria andSourceCodeLike(String value) {
            addCriterion("SOURCE_CODE like", value, "sourceCode");
            return this;
        }

        public Criteria andSourceCodeNotLike(String value) {
            addCriterion("SOURCE_CODE not like", value, "sourceCode");
            return this;
        }

        public Criteria andSourceCodeIn(List values) {
            addCriterion("SOURCE_CODE in", values, "sourceCode");
            return this;
        }

        public Criteria andSourceCodeNotIn(List values) {
            addCriterion("SOURCE_CODE not in", values, "sourceCode");
            return this;
        }

        public Criteria andSourceCodeBetween(String value1, String value2) {
            addCriterion("SOURCE_CODE between", value1, value2, "sourceCode");
            return this;
        }

        public Criteria andSourceCodeNotBetween(String value1, String value2) {
            addCriterion("SOURCE_CODE not between", value1, value2, "sourceCode");
            return this;
        }

        public Criteria andSourceTypeIsNull() {
            addCriterion("SOURCE_TYPE is null");
            return this;
        }

        public Criteria andSourceTypeIsNotNull() {
            addCriterion("SOURCE_TYPE is not null");
            return this;
        }

        public Criteria andSourceTypeEqualTo(Integer value) {
            addCriterion("SOURCE_TYPE =", value, "sourceType");
            return this;
        }

        public Criteria andSourceTypeNotEqualTo(Integer value) {
            addCriterion("SOURCE_TYPE <>", value, "sourceType");
            return this;
        }

        public Criteria andSourceTypeGreaterThan(Integer value) {
            addCriterion("SOURCE_TYPE >", value, "sourceType");
            return this;
        }

        public Criteria andSourceTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("SOURCE_TYPE >=", value, "sourceType");
            return this;
        }

        public Criteria andSourceTypeLessThan(Integer value) {
            addCriterion("SOURCE_TYPE <", value, "sourceType");
            return this;
        }

        public Criteria andSourceTypeLessThanOrEqualTo(Integer value) {
            addCriterion("SOURCE_TYPE <=", value, "sourceType");
            return this;
        }

        public Criteria andSourceTypeIn(List values) {
            addCriterion("SOURCE_TYPE in", values, "sourceType");
            return this;
        }

        public Criteria andSourceTypeNotIn(List values) {
            addCriterion("SOURCE_TYPE not in", values, "sourceType");
            return this;
        }

        public Criteria andSourceTypeBetween(Integer value1, Integer value2) {
            addCriterion("SOURCE_TYPE between", value1, value2, "sourceType");
            return this;
        }

        public Criteria andSourceTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("SOURCE_TYPE not between", value1, value2, "sourceType");
            return this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("CREATE_USER is null");
            return this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("CREATE_USER is not null");
            return this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("CREATE_USER =", value, "createUser");
            return this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("CREATE_USER <>", value, "createUser");
            return this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("CREATE_USER >", value, "createUser");
            return this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER >=", value, "createUser");
            return this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("CREATE_USER <", value, "createUser");
            return this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER <=", value, "createUser");
            return this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("CREATE_USER like", value, "createUser");
            return this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("CREATE_USER not like", value, "createUser");
            return this;
        }

        public Criteria andCreateUserIn(List values) {
            addCriterion("CREATE_USER in", values, "createUser");
            return this;
        }

        public Criteria andCreateUserNotIn(List values) {
            addCriterion("CREATE_USER not in", values, "createUser");
            return this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("CREATE_USER between", value1, value2, "createUser");
            return this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER not between", value1, value2, "createUser");
            return this;
        }

        public Criteria andCreateUsernameIsNull() {
            addCriterion("CREATE_USERNAME is null");
            return this;
        }

        public Criteria andCreateUsernameIsNotNull() {
            addCriterion("CREATE_USERNAME is not null");
            return this;
        }

        public Criteria andCreateUsernameEqualTo(String value) {
            addCriterion("CREATE_USERNAME =", value, "createUsername");
            return this;
        }

        public Criteria andCreateUsernameNotEqualTo(String value) {
            addCriterion("CREATE_USERNAME <>", value, "createUsername");
            return this;
        }

        public Criteria andCreateUsernameGreaterThan(String value) {
            addCriterion("CREATE_USERNAME >", value, "createUsername");
            return this;
        }

        public Criteria andCreateUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USERNAME >=", value, "createUsername");
            return this;
        }

        public Criteria andCreateUsernameLessThan(String value) {
            addCriterion("CREATE_USERNAME <", value, "createUsername");
            return this;
        }

        public Criteria andCreateUsernameLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USERNAME <=", value, "createUsername");
            return this;
        }

        public Criteria andCreateUsernameLike(String value) {
            addCriterion("CREATE_USERNAME like", value, "createUsername");
            return this;
        }

        public Criteria andCreateUsernameNotLike(String value) {
            addCriterion("CREATE_USERNAME not like", value, "createUsername");
            return this;
        }

        public Criteria andCreateUsernameIn(List values) {
            addCriterion("CREATE_USERNAME in", values, "createUsername");
            return this;
        }

        public Criteria andCreateUsernameNotIn(List values) {
            addCriterion("CREATE_USERNAME not in", values, "createUsername");
            return this;
        }

        public Criteria andCreateUsernameBetween(String value1, String value2) {
            addCriterion("CREATE_USERNAME between", value1, value2, "createUsername");
            return this;
        }

        public Criteria andCreateUsernameNotBetween(String value1, String value2) {
            addCriterion("CREATE_USERNAME not between", value1, value2, "createUsername");
            return this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("CREATE_TIME like", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("CREATE_TIME not like", value, "createTime");
            return this;
        }

        public Criteria andCreateTimeIn(List values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotIn(List values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return this;
        }

        public Criteria andModifyUsercodeIsNull() {
            addCriterion("MODIFY_USERCODE is null");
            return this;
        }

        public Criteria andModifyUsercodeIsNotNull() {
            addCriterion("MODIFY_USERCODE is not null");
            return this;
        }

        public Criteria andModifyUsercodeEqualTo(String value) {
            addCriterion("MODIFY_USERCODE =", value, "modifyUsercode");
            return this;
        }

        public Criteria andModifyUsercodeNotEqualTo(String value) {
            addCriterion("MODIFY_USERCODE <>", value, "modifyUsercode");
            return this;
        }

        public Criteria andModifyUsercodeGreaterThan(String value) {
            addCriterion("MODIFY_USERCODE >", value, "modifyUsercode");
            return this;
        }

        public Criteria andModifyUsercodeGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFY_USERCODE >=", value, "modifyUsercode");
            return this;
        }

        public Criteria andModifyUsercodeLessThan(String value) {
            addCriterion("MODIFY_USERCODE <", value, "modifyUsercode");
            return this;
        }

        public Criteria andModifyUsercodeLessThanOrEqualTo(String value) {
            addCriterion("MODIFY_USERCODE <=", value, "modifyUsercode");
            return this;
        }

        public Criteria andModifyUsercodeLike(String value) {
            addCriterion("MODIFY_USERCODE like", value, "modifyUsercode");
            return this;
        }

        public Criteria andModifyUsercodeNotLike(String value) {
            addCriterion("MODIFY_USERCODE not like", value, "modifyUsercode");
            return this;
        }

        public Criteria andModifyUsercodeIn(List values) {
            addCriterion("MODIFY_USERCODE in", values, "modifyUsercode");
            return this;
        }

        public Criteria andModifyUsercodeNotIn(List values) {
            addCriterion("MODIFY_USERCODE not in", values, "modifyUsercode");
            return this;
        }

        public Criteria andModifyUsercodeBetween(String value1, String value2) {
            addCriterion("MODIFY_USERCODE between", value1, value2, "modifyUsercode");
            return this;
        }

        public Criteria andModifyUsercodeNotBetween(String value1, String value2) {
            addCriterion("MODIFY_USERCODE not between", value1, value2, "modifyUsercode");
            return this;
        }

        public Criteria andModifyUsernameIsNull() {
            addCriterion("MODIFY_USERNAME is null");
            return this;
        }

        public Criteria andModifyUsernameIsNotNull() {
            addCriterion("MODIFY_USERNAME is not null");
            return this;
        }

        public Criteria andModifyUsernameEqualTo(String value) {
            addCriterion("MODIFY_USERNAME =", value, "modifyUsername");
            return this;
        }

        public Criteria andModifyUsernameNotEqualTo(String value) {
            addCriterion("MODIFY_USERNAME <>", value, "modifyUsername");
            return this;
        }

        public Criteria andModifyUsernameGreaterThan(String value) {
            addCriterion("MODIFY_USERNAME >", value, "modifyUsername");
            return this;
        }

        public Criteria andModifyUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFY_USERNAME >=", value, "modifyUsername");
            return this;
        }

        public Criteria andModifyUsernameLessThan(String value) {
            addCriterion("MODIFY_USERNAME <", value, "modifyUsername");
            return this;
        }

        public Criteria andModifyUsernameLessThanOrEqualTo(String value) {
            addCriterion("MODIFY_USERNAME <=", value, "modifyUsername");
            return this;
        }

        public Criteria andModifyUsernameLike(String value) {
            addCriterion("MODIFY_USERNAME like", value, "modifyUsername");
            return this;
        }

        public Criteria andModifyUsernameNotLike(String value) {
            addCriterion("MODIFY_USERNAME not like", value, "modifyUsername");
            return this;
        }

        public Criteria andModifyUsernameIn(List values) {
            addCriterion("MODIFY_USERNAME in", values, "modifyUsername");
            return this;
        }

        public Criteria andModifyUsernameNotIn(List values) {
            addCriterion("MODIFY_USERNAME not in", values, "modifyUsername");
            return this;
        }

        public Criteria andModifyUsernameBetween(String value1, String value2) {
            addCriterion("MODIFY_USERNAME between", value1, value2, "modifyUsername");
            return this;
        }

        public Criteria andModifyUsernameNotBetween(String value1, String value2) {
            addCriterion("MODIFY_USERNAME not between", value1, value2, "modifyUsername");
            return this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("MODIFY_TIME is null");
            return this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("MODIFY_TIME is not null");
            return this;
        }

        public Criteria andModifyTimeEqualTo(Date value) {
            addCriterion("MODIFY_TIME =", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeNotEqualTo(Date value) {
            addCriterion("MODIFY_TIME <>", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeGreaterThan(Date value) {
            addCriterion("MODIFY_TIME >", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME >=", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeLessThan(Date value) {
            addCriterion("MODIFY_TIME <", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("MODIFY_TIME <=", value, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeIn(List values) {
            addCriterion("MODIFY_TIME in", values, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeNotIn(List values) {
            addCriterion("MODIFY_TIME not in", values, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
            return this;
        }

        public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("MODIFY_TIME not between", value1, value2, "modifyTime");
            return this;
        }
    }
}